server:
  port: 8888  # 端口
  servlet:
    context-path : /hackathon  # 项目路径-上下文路径
spring:
  # 2.4版本之前spring.profiles.active = dev
#  config: # 2.4版本之后
#    activate:
#      on-profile:
#        - dev
  application:
    name: io-hackathon  # 应用名称

netty:
  port: 9999
  nThreads: 5000
  maxFrameLength: 10485760
  soBacklog: 1024