server:
  port: 8888  # 端口
  servlet:
    context-path : /hackathon  # 项目路径-上下文路径
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Small@521
    url: jdbc:mysql://192.168.230.129:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          #        dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
      hibernate:
        ddl-auto: update
  #      ddl-auto: create
  # 2.4版本之前spring.profiles.active = dev
#  config: # 2.4版本之后
#    activate:
#      on-profile:
#        - dev
  application:
    name: io-hackathon  # 应用名称

netty:
  port: 9999
  nThreads: 5000
  maxFrameLength: 10485760
  soBacklog: 1024

  logging:
    level: trace